---
# tasks file for Dell-Networking.dellos-dcb
 - name: "Provisioning DCB configuration for dellos9"
   dellos9_config:
      src: dellos9_dcb.j2
      provider: "{{ cli }}"
#   notify: save config os9
   when: ansible_net_os_name == "dellos9"
   register: output
